# Generated by Django 6.0 on 2025-12-14 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hh_id", models.IntegerField(unique=True, verbose_name="ID на HH")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "company_logo",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Логотип компании",
                    ),
                ),
                ("area_name", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "salary_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Зарплата от",
                    ),
                ),
                (
                    "salary_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Зарплата до",
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Валюта"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание вакансии")),
                (
                    "specialization",
                    models.CharField(max_length=255, verbose_name="Специализация"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-published_at"],
            },
        ),
    ]
