# Generated by Django 6.0 on 2025-12-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_searchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(max_length=255, verbose_name="Поисковый запрос"),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Регион"
                    ),
                ),
                (
                    "per_page",
                    models.IntegerField(default=20, verbose_name="Количество вакансий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "vacancies",
                    models.ManyToManyField(
                        blank=True,
                        to="vacancies.vacancy",
                        verbose_name="Найденные вакансии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поисковый запрос",
                "verbose_name_plural": "Поисковые запросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
